# Site settings
name: Kyle Shannon, Data Scientist
description: "Trying to decipher order from the chaos"
baseurl: ""
url: "http://kshannon.github.io"
twitter_username: ButFirstData
github_username:  kshannon

# Build Settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
theme: jekyll-theme-minimal